version: "3.9"

services:
  backend:
    build: ./backend
    container_name: taskmaster-backend
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=mysql
      - DB_USER=taskuser
      - DB_PASS=123
      - DB_NAME=taskmaster
      - PORT=4000
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: taskmaster-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: taskmaster
      MYSQL_USER: taskuser
      MYSQL_PASSWORD: Task@123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  frontend:
    build: ./frontend
    container_name: taskmaster-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql-data:
